version: "3.9"

x-common-environment: &common-environment
  DATABASE_URL: postgresql://postgres:password@db/weather_api_dev
  TEST_DATABASE_URL: postgresql://postgres:password@db/weather_api_test

services:
  weather_api:
    build:
      context: .
      target: api
    environment:
      <<: *common-environment
    entrypoint: "/usr/bin/entrypoint.sh"
    command: bundle exec puma -C config/puma.rb
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    networks:
      - weather_api
    restart: unless-stopped
    depends_on:
      - db
    stdin_open: true
    tty: true

  daemons:
    build:
      context: .
      target: daemons
    environment:
      <<: *common-environment
    networks:
      - weather_api
    volumes:
      - .:/app
    entrypoint: "/usr/bin/daemons_entrypoint.sh"
    command: bundle exec bin/delayed_job start
    depends_on:
      - db
      - weather_api

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./tmp/db_data:/var/lib/postgresql/data
    networks:
      - weather_api
    
networks:
  weather_api:
    driver: bridge
