version: "3.3"

services:
  weather_api:
    build:
      context: .
    environment:
      DATABASE_URL: postgresql://postgres:password@db/weather_api_dev
      TEST_DATABASE_URL: postgresql://postgres:password@db/weather_api_test
    entrypoint: "/usr/bin/entrypoint.sh"
    command: bundle exec puma -C config/puma.rb
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    networks:
      - weather_api
    restart: unless-stopped
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./tmp/db_data:/var/lib/postgresql/data
    
networks:
  weather_api:
    driver: bridge
